### PR TITLE
Updaing the navbar for HX, moar variables

### PR DESCRIPTION
**Pull request by jodiedoubleday**
#### What does this PR do? (please provide any background)
- During project lounge i took it upon myself to tidy the tripapp styling. starting with the stuff at the very top.. the navbar.
- The current branding only really touched the basic styling of a navbar, and even includes stuff we have never and may never use.
- This PR tdying the the existing styles and add's real word branding and styling to existing but cleaned html.

#### What tests does this PR have?
None

#### How can this be tested?
- Yu can check this out in the Pattern Library
- Make sure you have `ui-brand-hx` locally and have switched to the branch `navbar`
- Navigate to the pattern library directory on your machine and checkout `navbar`
- `npm link ../ui-brand-hx` assuming pattern library and brand are in the same parent folder
- now `npm start` and look at navbar in organisms section.
- Test in both mobile and desktop

#### Screenshots / Screencast
screen shot 2016-01-18 at 17 09 46
screen shot 2016-01-18 at 17 09 56

#### What gif best describes how you feel about this work?
Flight of the Conhords

---

- [x] I have checked our general [contributing document](https://github.com/holidayextras/culture/blob/master/CONTRIBUTING.md) and the project specific [contributing document](../blob/master/CONTRIBUTING.md) (if present) and I'm happy for this to be reviewed.

#### Reviewers

**Review 1**
- [x] :+1:

**Review 2** \*
- [x] :+1:

**Review 3** _(optional)_
- [ ] :+1:

By adding a +1 you are confirming you have...
- Witnessed the work behaving as expected (this could be on the author's machine or screencast).
- Checked for coding anti-patterns.
- Checked for appropriate test coverage.
- Checked all the tests are passing.

\*  for HX this review must be completed by an SE, SA or Project Guru

### CODE REVIEW

**Comment by elliottcrush** [comment]
:+1:

**Comment by jamesmcneil** [comment]
Taking :two:

**Comment by jamesmcneil** [comment]
Using iOS Simulator `Your account` on mobile is truncated on iphone 6s, also should bookings in the expanded menu be truncated when there is empty space to the right? http://grab.by/NvMC

**Comment by jodiedoubleday** [comment]
I've fixed the expanded menu truncating issue.
The "your account" being truncated is intentional, anything over a certain size gets shrunk (mainly for german big long words)

Ready to re-test

**Comment by jamesmcneil** [comment]
Looks good http://grab.by/NxHC :shipit:

**Comment by elliottcrush** [comment]
FYI @rahulpatel @Arditc @djbeaumont

**Pull request merged**
